config/routes.rb
Rails.application.routes.draw do
  #Routes only for singin/signout
  devise_for :users, only: :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#home", as: 'home'
  get 'bio', to: 'posts#bio', as: 'bio'
  get 'admin', to: 'posts#admin', as: 'admin'

  scope '/admin' do
    get 'projects', to: 'posts#project_manager', as: 'projects_manager'
    get 'stories', to: 'posts#story_manager', as: 'stories_manager'
  end

  #Nesting of routes for creating comments
  concern :commentable do
    resources :comments, only: [:new, :create]
  end
  #Routes for posts
  resources :projects, param: :title, concerns: :commentable
  resources :stories, param: :title, concerns: :commentable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  #Model relation
  belongs_to :post
  #Requisite for creation
  validates :author, presence: true
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  #Requisite for model creation
  validates :title, presence: true
  validates :content, presence: true
  enum status: [ :project, :working, :completed ]
  #Relation between models
  has_many :comments, dependent: :delete_all
  #Adding images to the model with Active Storage
  has_one_attached :cover
  has_many_attached :images

  #Instead of ID's param in URL
  def to_param
    title
  end

  #Methods
  def reading_time
    words = self.content.split(" ").count
    time = (words.fdiv(200).round(1))*60.round
    minutes = time.div(60)
    "#{minutes} min read"
  end

  def self.categories
    all_cats = []
    Post.all.each do |post|
      post.categories.split(",").each do |category|
        all_cats << category
      end
    end
    all_cats.uniq
  end

  def self.search_by_category
    # TODO
    # => Array of posts
  end

end

app/models/project.rb
class Project < Post
end

app/models/story.rb
class Story < Post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @post = Post.find_by(title: params[:project_title] || params[:story_title] )
    @comment.post = @post
    #Part of Ajaxification of the comments
    if @comment.save
      respond_to do |format|
        format.html { redirect_to project_path(@post) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'projects/show' || 'stories/show'}
        format.js  # <-- idem
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :content, :email)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # Devise Authentication for admin page
  protect_from_forgery
  before_action :authenticate_user!, only: [:admin]

  def home
    @projects = Project.all
    @stories = Story.all
    @recent = Post.all.last(3)
  end

  def bio
  end

  def admin
    @project = Project.new()
    @story = Story.new()
  end

  def project_manager
    @projects = Project.all
  end

  def story_manager
    @stories = Story.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  #Securing the creation of models only with authentication of the admin w/Devise
  protect_from_forgery
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]


  def index
    @projects = Project.all
    # Add recent projects
  end

  def show
    @project = Project.find_by(title: params[:title])
    @title = @project.title
    @content = @project.content.split("\n")
    @year = @project.year
    @status = @project.status
    @author = @project.author
    @collaborators = @project.collaborators
    @software = @project.software.split(",").map{|w| w.capitalize.strip }.join(", ")
    @reading_time = @project.reading_time
    @categories = @project.categories.split(",").map{ |c| "##{c.strip}" }
    @likes = @project.likes
    @comments = @project.comments
    @comment = Comment.new()
    @post = @project
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.save
    @project.cover.attach(params[:project][:cover]) if params[:project][:cover]
    @project.images.attach(params[:project][:images]) if params[:project][:images]
    redirect_to admin_path
  end

  def edit
    @project = Project.find_by(title: params[:title])
  end

  def update
    @project = Project.find_by(title: params[:title])
    @project.update(project_params)
    redirect_to admin_path
  end

  def destroy
    @project = Project.find_by(title: params[:title])
    @project.destroy
    redirect_to admin_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :year, :software, :status, :content, :categories, :collaborators, :author, :images, :cover)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  #Securing the creation of models only with authentication of the admin w/Devise
  protect_from_forgery
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @stories = Story.all
    #Add recent stories
  end

  def show
    @story = Story.find_by(title: params[:title])
    @title = @story.title
    @content = @story.content
    @author = @story.author
    @reading_time = @story.reading_time
    @categories = @story.categories.split(",").map { |c| "##{c}" }
    @likes = @story.likes
    @comments = @story.comments
    @comment = Comment.new()
    @post = @story
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    @story.save
    #Saving images with Active Storage
    @story.cover.attach(params[:story][:cover]) if params[:story][:cover]
    @story.images.attach(params[:story][:images]) if params[:story][:images]
    redirect_to admin_path
  end

  private

  #Method that secures the params got in the form
  def story_params
    params.require(:story).permit(:title, :content, :categories, :author, :images, :cover)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/storys_helper.rb
module StorysHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for([ post, comment ], remote: true) do |f| %>
  <%= f.input :author, placeholder: 'your name' %>
  <%= f.input :content, as: :string, placeholder: 'write something here...' %>
  <%= f.submit 'post' %>
<% end %>

app/views/comments/_show.html.erb
  <div  id="comments">
    <% if comments.blank? %>
      <p>Be the first to leave a comment :) </p>
    <% else %>
      <% comments.each do |comment| %>
      <%= render 'shared/comment', comment: comment %>
      <% end %>
    <% end %>
</div>

app/views/comments/create.js.erb
function refreshForm(innerHTML) {
  const newCommentForm = document.getElementById('new_comment');
  newCommentForm.innerHTML = innerHTML;
}

function addComment(commentsHTML) {
  const comments = document.getElementById('comments');
  comments.insertAdjacentHTML('beforeend', commentsHTML);
}

<% if @comment.errors.any? %>
  refreshForm('<%= j render "comments/form", post: @post, comment: @comment%>');
<% else %>
  addComment('<%= j render "shared/comment", comment: @comment %>');
  refreshForm('<%= j render "comments/form", post: @post, comment: Comment.new() %>');
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Daniel Polo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/posts/admin.html.erb
<% content_for :title, "Admin" %>
<div class="container">
  <div class="admin innerheight">
    <div class="row">
      <div class="admin-manage col-sm-6">
        <div class="admin-header">
          <h1>projects</h1>
        </div>
        <div class="admin-action">
          <%= link_to "publish new project", new_project_path %>
        </div>
        <div class="admin-action">
          <%= link_to "manage projects", projects_manager_path %>
        </div>
      </div>
      <div class="admin-manage col-sm-6">
        <div class="admin-header">
          <h1>posts</h1>
        </div>
        <div class="admin-action">
          <%= link_to "write new story", new_story_path %>
        </div>
        <div class="admin-action">
          <%= link_to "manage stories", stories_manager_path %>
        </div>
      </div>
      <div class="col-sm-12">
        <div class="admin-action close-session">
          <%= link_to "close session", destroy_user_session_path, method: :delete %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/bio.html.erb
<% content_for :title, "About" %>
<div class="container">
  <div class="row flex-fullheight align-items-center">
    <div class="bio-desc col-md-12">
      <h1>Daniel Polo is a male-type creative technologist. He is crazy for the internet, sci-fi, arts and media. After graduating from the Architecture School in Mexico City, Daniel Polo paused his architecture passion searching for new ones... then coding came to him.<br>He is a curious young man who always wants to understand "how" everything, so Daniel <em>googles</em> a lot. He also thinks he's been cursed because of that.<br><br>Daniel Polo <span><%= icon('fas', 'heart') %></span> espresso and tacos.</h1>
    </div>
  </div>
    <div class="bio-social col-md-12">
      <div class="icons">
        <%= link_to icon('fab', 'facebook'), "https://www.facebook.com/danielpolo/", class: 'hover-blue' %>
        <%= link_to icon('fab', 'instagram'), "https://www.instagram.com/danielppolo/", class: 'hover-red' %>
        <%= link_to icon('fab', 'behance'), "https://www.behance.net/danielppolo/", class: 'hover-blue' %>
        <%= link_to icon('fab', 'pinterest'), "https://www.pinterest.com/danielppolo/", class: 'hover-red' %>
        <%= link_to icon('fab', 'twitter'), "https://www.twitter.com/danielppolo_/", class: 'hover-blue' %>
        <%= link_to icon('fab', 'github'), "https://www.github.com/danielppolo/", class: 'hover-red' %>
      </div>
    </div>
</div>

<%= render 'shared/footer' %>

app/views/posts/home.html.erb
<% content_for :title, "Home" %>
<div id="main_carousel" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner fullheight">

    <% @recent.each_with_index do |post, i| %>
    <div class="carousel-item <%= "active" if i == 0 %>">
      <a href="<%= project_path(post) %>">
        <div class="carousel-img fullfill" style='background-image: url("<%= url_for(post.cover) %>");'>
          <h1 class="carousel-title d-none d-md-block">
            <%= post.class == Project ? "featured project" : "featured story" %>
            <br><%= post.title.downcase %></h1>
        </div>
      </a>
    </div>
  <% end %>
  </div>
</div>

app/views/posts/project_manager.html.erb
<% content_for :title, "Manage" %>
<% @projects.each do |project| %>
  <div>
    <h2>
      <%= project.title %>
      <%= link_to "show", project_path(project) %>
      <%= link_to "edit", edit_project_path(project) %>
      <%= link_to "delete", project_path(project), method: :delete %>
    </h2>
  </div>
<% end %>

app/views/posts/story_manager.html.erb
<% content_for :title, "Manage" %>
<% @stories.each do |story| %>
  <div>
    <h2>
      <%= story.title %>
      <%= link_to "show", story_path(story) %>
      <%= link_to "edit", edit_story_path(story) %>
      <%= link_to "delete", story_path(story), method: :delete %>
    </h2>
  </div>
<% end %>

app/views/projects/edit.html.erb
<% content_for :title, "Edit" %>
<div class="container">
  <div class="admin">
    <div class="new-post">
      <h1>edit project</h1>
      <%= simple_form_for @project, method: :patch, html: {multipart: true} do |f| %>
      <%= f.input :title, placeholder: 'project name' %>
      <%= f.input :year, placeholder: 'year', collection: (Date.today.year.to_i - 6)..Date.today.year.to_i, selected: Date.today.year.to_i %>
      <%= f.input :status, placeholder: 'status',collection: Post.statuses.keys, selected: 0%>
      <%= f.input :author, placeholder: 'author' %>
      <%= f.input :collaborators, placeholder: 'collaborators w/commas' %>
      <%= f.input :categories, placeholder: 'categories w/commas' %>
      <%= f.input :software, placeholder: 'software  w/commas' %>
      <%= f.input :content, placeholder: 'project description' %>
      <%= f.input :cover, as: :file, label: 'upload cover picture' %>
      <%= f.input :images, as: :file, label: 'upload pictures', input_html: {  multiple: true } %>
      <%= f.submit 'publish project' %>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<% content_for :title, "Work" %>
<div class="container">
  <div class="row flex-innerheight">
    <% @projects.each do |project| %>
    <a class="posts-item col-md-12" href="<%= project_path(project) %>">
      <div class="posts-img" style="background-image: url('<%= url_for(project.cover) if project.cover.attached? %>');">
        <div class="posts-text">
          <h1><%= project.title%></h1>
        </div>
      </div>
    </a>
    <% end %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/projects/new.html.erb
<div class="container">
  <div class="admin">
    <div class="new-post">
      <h1>new project</h1>
      <%= simple_form_for @project, html: {multipart: true} do |f| %>
      <%= f.input :title, placeholder: 'project name' %>
      <%= f.input :year, placeholder: 'year', collection: (Date.today.year.to_i - 6)..Date.today.year.to_i, selected: Date.today.year.to_i %>
      <%= f.input :status, placeholder: 'status',collection: Post.statuses.keys, selected: 0%>
      <%= f.input :author, placeholder: 'author' %>
      <%= f.input :collaborators, placeholder: 'collaborators w/commas' %>
      <%= f.input :categories, placeholder: 'categories w/commas' %>
      <%= f.input :software, placeholder: 'software  w/commas' %>
      <%= f.input :content, placeholder: 'project description' %>
      <!--%= f.input :cover, as: :file, label: 'upload cover picture' %-->
      <!--%= f.input :images, as: :file, label: 'upload pictures', input_html: {  multiple: true } direct_upload: true %-->
      <%= f.input :cover do %>
        <%= f.file_field :cover, direct_upload: true %>
      <% end %>
      <%= f.input :images do %>
        <%= f.file_field :images, multiple: true, direct_upload: true %>
      <% end %>
      <%= f.submit 'publish project' %>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<% content_for :title, "Work" %>
<% if @project.cover.attached? %>
<div class="post-cover parallax-window" data-parallax="scroll" data-image-src="<%= url_for(@project.cover) %>"></div>
<% end %>

<div class="container">
  <div class=" row post-headline align-items-center">
    <div class="col-sm-6">
      <h1><%= @title if @title %></h1>
      <p><%= @year if @year%></p>
    </div>
    <div class="col-sm-6 ">
      <p><%= @content.first if @content%></p>
    </div>
  </div>

  <div class="row">
    <% if @project.images.attached? %>
      <% @project.images.each do |i| %>
        <div class="col-sm-12 post-img">
          <%= image_tag i, class: "fullfill" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>



<%= render 'shared/feedback' %>
<%= render 'shared/footer' %>
<%= javascript_pack_tag "like" %>
<%= javascript_pack_tag "parallax" %>

app/views/shared/_comment.html.erb
<div class="comment">
  <h2><%= comment.author.downcase %></h2>
  <p><%= comment.content %></p>
</div>

app/views/shared/_feedback.html.erb
<div class="feedback">
  <div class="container">
    <%= render 'shared/like' %>
    <h1>comments</h1>
    <%= render 'comments/show', comments: @comments %>
    <%= render 'comments/form', post: @post, comment: @comment %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="portfolio-footer">
  <div class="container">
    <div class="footer-mssg col-sm-12">
      <h1>Any inquiries or professional opportunities are warmly welcomed.</h1>
      <a href="mailto:test@gmail.com" >Feel free to say Hola!</a>
    </div>
  </div>
</div>

app/views/shared/_like.html.erb
<div class="like-btn">
  <h2>if you like it, let me know</h2>
  <div class="heart"></div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top portfolio-nav">
  <div class="container">
    <div class="nav-element"><%= link_to 'work', projects_path, class: 'nav-links' %></div>
    <div class="nav-element"> <%= link_to 'me', bio_path, class: 'nav-links' %></div>
    <div class="nav-element"><%= link_to 'blog', stories_path, class: 'nav-links' %></div>
  </div>
</nav>

app/views/stories/edit.html.erb
<% content_for :title, "Edit" %>
<div class="container">
  <div class="admin">
    <div class="new-post">
      <h1>edit story</h1>
      <%= simple_form_for @story, method: :patch do |f| %>
      <%= f.input :title, placeholder: 'story title' %>
      <%= f.input :author, placeholder: 'who wrote it?' %>
      <%= f.input :categories, placeholder: 'categories w/commas' %>
      <%= f.input :content, placeholder: 'begin writting...' %>
      <%= f.input :cover, as: :file, label: 'upload cover picture' %>
      <%= f.input :images, as: :file, label: 'upload pictures', multiple: true %>
      <%= f.submit 'post story' %>
      <% end %>
    </div>
  </div>
</div>

app/views/stories/index.html.erb
<% content_for :title, "Blog" %>
<div class="container">
  <div class="row flex-innerheight">
    <% @stories.each do |story| %>
    <a class="posts-s-item col-md-12 col-xs-12" href="<%= story_path(story) %>">
      <div class="posts-s-img">
        <div class="posts-s-text">
          <h1><%= story.title%></h1>
          <p><%= story.reading_time %></p>
        </div>
        <div class="posts-s-content">
          <p><%= story.content %></p>
        </div>
      </div>
    </a>
    <% end %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/stories/new.html.erb
<% content_for :title, "New" %>
<div class="container">
  <div class="admin">
    <div class="new-post">
      <h1>new story</h1>
      <%= simple_form_for @story do |f| %>
      <%= f.input :title, placeholder: 'story title' %>
      <%= f.input :author, placeholder: 'who wrote it?' %>
      <%= f.input :categories, placeholder: 'categories w/commas' %>
      <%= f.input :content, placeholder: 'begin writting...' %>
      <!--%= f.input :cover, as: :file, label: 'upload cover picture' %-->
      <!--%= f.input :images, as: :file, label: 'upload pictures', multiple: true %-->
      <%= f.input :cover do %>
        <%= f.file_field :cover, direct_upload: true %>
      <% end %>
      <%= f.input :images do %>
        <%= f.file_field :images, multiple: true, direct_upload: true %>
      <% end %>
      <%= f.submit 'post story' %>
      <% end %>
    </div>
  </div>
</div>

app/views/stories/show.html.erb
<% content_for :title, "Blog" %>
<div class="story-post">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-sm-12 text-center story-title">
        <h1><%= @title if @title %></h1>
      </div>
      <div class="col-sm-12 text-center story-details">
        <p><%= @reading_time if @content %></p>
      </div>
      <div class="col-sm-10 text-center story-content">
        <p><%= @content if @content%></p>
      </div>

    <% if @story.images.attached? %>
      <% @story.images.each do |i| %>
        <div class="col-sm-12">
          <%= image_tag i, class: "fullfill" %>
        </div>
      <% end %>
    <% end %>

    </div>
  </div>
</div>


<%= render 'shared/feedback' %>
<%= render 'shared/footer' %>
<%= javascript_pack_tag "like" %>
<%= javascript_pack_tag "parallax" %>